In [1]:
import pandas as pd
import numpy as np


#declaro la ruta
ruta = r"C:\Users\rikar\OneDrive\Documents\Gitlab\TranquiTest\csv"
outpout =  r"C:\Users\rikar\OneDrive\Documents\Gitlab\TranquiTest\csv clean files"

class data_wrangling():
    
   
    #inicializo variables
    def __init__(self):
        self.__deliveries = pd.read_csv(f"{ruta}\\deliveries.csv")
        self.__users = pd.read_csv(f"{ruta}\\users.csv")
        self.__segments = pd.read_csv(f"{ruta}\\segments.csv")
      
        
        
    #exploro datos para verificar si hay datos nulos
    def exploring_data(self):
        
        
        nullable_val_deliveries = self.__deliveries.isnull().sum()
        nullable_val_users = self.__users.isnull().sum()
        nullable_val_segments = self.__segments.isnull().sum()
        
        return nullable_val_deliveries, nullable_val_users,nullable_val_segments
    
    #exploro los tipos de datos
    def exploring_types(self):
        
        deliveries_types= self.__segments.dtypes
        users_types= self.__users.dtypes
        segments_types= self.__segments.dtypes
        return deliveries_types,users_types , segments_types
        
    #formateo las columnas necesarias de los dataframes
    def formating_columns(self):
        
        self.__segments.loc[:,'fecha_evolucion'] = pd.to_datetime(self.__segments.fecha_evolucion)
        return self.__segments
    
    #primera exploracion para verificar la calidad de los datos
    def finding_duplicates(self):
        
        segments = self.__segments.describe(include='all',datetime_is_numeric=True )
        users = self.__users.describe(include='all' )
        deliveries  = self.__deliveries.describe(include='all' )
        return segments,users,deliveries
            
    #verificando ,eliminando duplicados y nulos y exportando la data- - segments
    def exploring_duplicates_segments(self):
        
        clean_segments = pd.DataFrame()
        
        if self.__segments.isnull().sum().sum()==0:
            self.__segments= self.__segments[~self.__segments.duplicated(subset=['fecha_evolucion','document'],keep=False)].drop_duplicates()
            self.__segments.to_csv(f"{outpout}\\segments.csv",index=False)
            return self.__segments

        if self.__segments.isnull().sum().sum() >0:
            self.__segments= self.__segments[~self.__segments.duplicated(subset=['fecha_evolucion','document'],keep=False)].drop_duplicates().dropna()
            self.__segments.to_csv(f"{outpout}\\segments.csv",index=False)
            return self.__segments

        
        #verificando ,eliminando duplicados y nulos y exportando la data- - users
    def exploring_duplicates_users(self):
            
        if  self.__users.isnull().sum().sum()==0:
            self.__users = self.__users[~self.__users.duplicated(subset=['user_id','document'],keep=False)].drop_duplicates()
            self.__users.to_csv(f"{outpout}\\users.csv",index=False)
            return self.__users 

        if self.__users.isnull().sum().sum()>0:
            self.__users  = self.__users [~self.__users .duplicated(subset=['user_id','document'],keep=False)].drop_duplicates().dropna()
            self.__users.to_csv(f"{outpout}\\users.csv",index=False)
            return self.__users 
    
       #verificando ,eliminando duplicados y nulos y exportando la data- deliveries
    def exploring_duplicates_deliveries(self):
    
        
        if  self.__deliveries.isnull().sum().sum()==0 :
            self.__deliveries = self.__deliveries[~self.__deliveries.duplicated(keep=False)].drop_duplicates()
            self.__deliveries.to_csv(f"{outpout}\\deliveries.csv",index=False)
            return self.__deliveries
        
        
        if self.__deliveries.isnull().sum().sum()>0:
            self.__deliveries = self.__deliveries[~self.__deliveries.duplicated(keep=False)].drop_duplicates().dropna(subset=['user_id'])
            self.__deliveries.to_csv(f"{outpout}\\deliveries.csv",index=False)
            return self.__deliveries

In [2]:
data_wrangling = data_wrangling()
data_wrangling.exploring_data()

C:\Users\rikar\AppData\Local\Temp/ipykernel_15568/2227672255.py:1: DtypeWarning: Columns (12,14,20,22,24) have mixed types.Specify dtype option on import or set low_memory=False.
  data_wrangling = data_wrangling()

(user_id                     65
 campaign_id                  0
 campaign_name            60114
 channel                      0
 failure_message         561682
 created                      0
 created_rfc3339              0
 sent                     86190
 sent_rfc3339             86190
 delivered               118920
 delivered_rfc3339       118920
 opened                  652403
 opened_rfc3339          652403
 clicked                 671736
 clicked_rfc3339         671736
 converted               669699
 converted_rfc3339       669699
 bounced                 655794
 bounced_rfc3339         655794
 spammed                 673569
 spammed_rfc3339         673569
 unsubscribed            673543
 unsubscribed_rfc3339    673543
 suppressed              673205
 suppressed_rfc3339      673205
 failed                  588268
 failed_rfc3339          588268
 dtype: int64,
 user_id       0
 created_at    0
 document      0
 dtype: int64,
 fecha_evolucion    0
 document           0
 segment            0
 dtype: int64)

In [3]:
data_wrangling.exploring_types()

(fecha_evolucion    object
 document            int64
 segment            object
 dtype: object,
 user_id        int64
 created_at    object
 document      object
 dtype: object,
 fecha_evolucion    object
 document            int64
 segment            object
 dtype: object)

In [4]:
data_wrangling.formating_columns()

      fecha_evolucion    document  segment
0          2021-09-30    32615537      E30
1          2021-09-30  1107048537      E30
2          2021-09-30    32615537      E30
3          2021-09-30  1107048537      E30
4          2021-09-30    10260928      E30
...               ...         ...      ...
47927      2021-10-31    98495415  CASTIGO
47928      2021-10-31      337042  CASTIGO
47929      2021-10-31      589859  CASTIGO
47930      2021-10-31      519529  CASTIGO
47931      2021-10-31      171913  CASTIGO

[47932 rows x 3 columns]

In [5]:
data_wrangling.finding_duplicates()

(                   fecha_evolucion      document segment
 count                        47932  4.793200e+04   47932
 unique                         NaN           NaN       7
 top                            NaN           NaN     E30
 freq                           NaN           NaN   17579
 mean    2021-10-15 03:05:25.360928  3.946758e+08     NaN
 min            2021-09-30 00:00:00  1.761000e+03     NaN
 25%            2021-09-30 00:00:00  2.250379e+07     NaN
 50%            2021-09-30 00:00:00  6.343634e+07     NaN
 75%            2021-10-31 00:00:00  1.026288e+09     NaN
 max            2021-10-31 00:00:00  8.909173e+09     NaN
 std                            NaN  4.944951e+08     NaN,
              user_id               created_at    document
 count   89942.000000                    89942       89942
 unique           NaN                    22712       89931
 top              NaN  2021-07-07 19:35:27.100  1112879476
 freq             NaN                    14753           2
 mean    49125.492417                      NaN         NaN
 std     27221.910805                      NaN         NaN
 min      2462.000000                      NaN         NaN
 25%     25610.250000                      NaN         NaN
 50%     49081.500000                      NaN         NaN
 75%     71954.750000                      NaN         NaN
 max     99442.000000                      NaN         NaN,
              user_id    campaign_id campaign_name channel  \
 count   6.735110e+05  673576.000000        613462  673576
 unique           NaN            NaN            27       4
 top              NaN            NaN       Castigo     sms
 freq             NaN            NaN        168129  412938
 mean    3.833764e+05      97.372792           NaN     NaN
 std     3.172442e+07      11.193853           NaN     NaN
 min     2.489000e+03      10.000000           NaN     NaN
 25%     4.699300e+04      95.000000           NaN     NaN
 50%     6.875500e+04     100.000000           NaN     NaN
 75%     8.063700e+04     103.000000           NaN     NaN
 max     3.215880e+09     108.000000           NaN     NaN

                                           failure_message       created  \
 count                                              111894  6.735760e+05
 unique                                                643           NaN
 top     Twilio Error 21606: The From phone number +571...           NaN
 freq                                                36874           NaN
 mean                                                  NaN  1.634744e+09
 std                                                   NaN  9.970649e+05
 min                                                   NaN  1.605743e+09
 25%                                                   NaN  1.633972e+09
 50%                                                   NaN  1.634662e+09
 75%                                                   NaN  1.635436e+09
 max                                                   NaN  1.636500e+09

                 created_rfc3339          sent             sent_rfc3339  \
 count                    673576  5.873860e+05                   587386
 unique                     7226           NaN                    15507
 top     2021-11-05 23:32:55.000           NaN  2021-10-12 22:03:17.000
 freq                        792           NaN                     1175
 mean                        NaN  1.634765e+09                      NaN
 std                         NaN  1.007722e+06                      NaN
 min                         NaN  1.605743e+09                      NaN
 25%                         NaN  1.633968e+09                      NaN
 50%                         NaN  1.634663e+09                      NaN
 75%                         NaN  1.635458e+09                      NaN
 max                         NaN  1.636500e+09                      NaN

            delivered  ...       bounced          bounced_rfc3339  \
 count   5.546560e+05  ...  1.778200e+04                    17782
 unique           NaN  ...           NaN                    12398
 top              NaN  ...           NaN  2021-10-15 16:39:42.000
 freq             NaN  ...           NaN                       17
 mean    1.634753e+09  ...  1.634884e+09                      NaN
 std     1.005362e+06  ...  1.137517e+06                      NaN
 min     1.605743e+09  ...  1.606163e+09                      NaN
 25%     1.633810e+09  ...  1.633986e+09                      NaN
 50%     1.634661e+09  ...  1.634749e+09                      NaN
 75%     1.635451e+09  ...  1.636149e+09                      NaN
 max     1.636500e+09  ...  1.636499e+09                      NaN

              spammed          spammed_rfc3339  unsubscribed  \
 count   7.000000e+00                        7  3.300000e+01
 unique           NaN                        7           NaN
 top              NaN  2021-11-04 19:15:36.000           NaN
 freq             NaN                        1           NaN
 mean    1.635087e+09                      NaN  1.634442e+09
 std     1.191363e+06                      NaN  7.488687e+05
 min     1.633574e+09                      NaN  1.633537e+09
 25%     1.633945e+09                      NaN  1.633714e+09
 50%     1.635982e+09                      NaN  1.634336e+09
 75%     1.636053e+09                      NaN  1.634832e+09
 max     1.636053e+09                      NaN  1.636291e+09

            unsubscribed_rfc3339    suppressed       suppressed_rfc3339  \
 count                        33  3.710000e+02                      371
 unique                       33           NaN                      269
 top     2021-10-29 00:50:18.000           NaN  2021-10-14 17:32:52.000
 freq                          1           NaN                        9
 mean                        NaN  1.634919e+09                      NaN
 std                         NaN  4.404496e+05                      NaN
 min                         NaN  1.634053e+09                      NaN
 25%                         NaN  1.634666e+09                      NaN
 50%                         NaN  1.635012e+09                      NaN
 75%                         NaN  1.635287e+09                      NaN
 max                         NaN  1.635459e+09                      NaN

               failed           failed_rfc3339
 count   8.530800e+04                    85308
 unique           NaN                    21965
 top              NaN  2021-10-14 00:30:20.000
 freq             NaN                       86
 mean    1.634592e+09                      NaN
 std     8.925425e+05                      NaN
 min     1.605752e+09                      NaN
 25%     1.634078e+09                      NaN
 50%     1.634413e+09                      NaN
 75%     1.635194e+09                      NaN
 max     1.636494e+09                      NaN

 [11 rows x 27 columns])

In [6]:
data_wrangling.exploring_duplicates_segments()

      fecha_evolucion  document  segment
56         2021-09-30   4318839      E30
57         2021-09-30   6391758      E30
58         2021-09-30  16264675      E30
59         2021-09-30  17866360      E30
60         2021-09-30  19472814      E30
...               ...       ...      ...
47927      2021-10-31  98495415  CASTIGO
47928      2021-10-31    337042  CASTIGO
47929      2021-10-31    589859  CASTIGO
47930      2021-10-31    519529  CASTIGO
47931      2021-10-31    171913  CASTIGO

[46587 rows x 3 columns]

In [7]:
data_wrangling.exploring_duplicates_users()

       user_id               created_at    document
0        68357  2021-08-13 14:12:03.857  1039089624
1        70324  2021-09-04 21:42:39.871    72333888
2        40297  2021-06-05 17:57:10.352  1144096686
3        53516  2021-07-07 19:35:27.100  1037612655
4        36142  2021-05-07 14:14:38.187  1130626764
...        ...                      ...         ...
89937    48524  2021-07-07 19:35:27.100    31658622
89938    40862  2021-06-05 17:57:10.352    40878433
89939    98447  2021-11-05 20:08:32.732    43664091
89940    59346  2021-07-13 17:52:17.683  1075870060
89941    51324  2021-07-07 19:35:27.100    79286818

[89942 rows x 3 columns]

In [8]:
data_wrangling.exploring_duplicates_deliveries()

,user_id,campaign_id,campaign_name,channel,failure_message,created,created_rfc3339,sent,sent_rfc3339,delivered,...,bounced,bounced_rfc3339,spammed,spammed_rfc3339,unsubscribed,unsubscribed_rfc3339,suppressed,suppressed_rfc3339,failed,failed_rfc3339
0,25748.0,26,Cierre de Solicitud Abono y NPS,sms,NaN,1636499723,2021-11-09 23:15:23.000,1.636500e+09,2021-11-09 23:15:24.000,1.636500e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,55986.0,103,Mora 60 90 y 120 con NORMALIZACION,sms,NaN,1636498653,2021-11-09 22:57:33.000,1.636499e+09,2021-11-09 22:57:34.000,1.636499e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,85791.0,95,CrediExpress Sin Alternativa,failed,Variable 'customer.phone' is missing,1636498228,2021-11-09 22:50:28.000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,85239.0,95,CrediExpress Sin Alternativa,failed,Variable 'customer.phone' is missing,1636498228,2021-11-09 22:50:28.000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,85730.0,95,CrediExpress Sin Alternativa,failed,Variable 'customer.phone' is missing,1636498228,2021-11-09 22:50:28.000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
673506,21884.0,26,Cierre de Solicitud Abono y NPS,email,NaN,1633047922,2021-10-01 00:25:22.000,1.633048e+09,2021-10-01 00:25:23.000,1.633048e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
673507,62855.0,26,Cierre de Solicitud Abono y NPS,email,NaN,1633047852,2021-10-01 00:24:12.000,1.633048e+09,2021-10-01 00:24:14.000,1.633048e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
673508,17100.0,26,Cierre de Solicitud Abono y NPS,sms,NaN,1633047627,2021-10-01 00:20:27.000,1.633048e+09,2021-10-01 00:20:28.000,1.633048e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
673509,10874.0,26,Cierre de Solicitud Abono y NPS,email,NaN,1633047437,2021-10-01 00:17:17.000,1.633047e+09,2021-10-01 00:17:17.000,1.633047e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
673510,63506.0,26,Cierre de Solicitud Abono y NPS,sms,NaN,1633046722,2021-10-01 00:05:22.000,1.633047e+09,2021-10-01 00:05:23.000,1.633047e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN